### PR TITLE
Bump libavif to v1.0.1

### PR DESCRIPTION
**Pull request by bbhtt**
See https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/46

### CODE REVIEW

**Comment by bbhtt** [comment]
I've started a PR to make kimageformats5 with heif support available in the runtime in https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/152

If all goes well, it needs to be removed from here too.

**Comment by bbhtt** [comment]
https://github.com/AOMediaCodec/libavif/blob/d1c26facaf5a8a97919ceee06814d05d10e25622/CMakeLists.txt#L547

**Comment by deepbluev7** [comment]
Thank you!

**Comment by deepbluev7** [comment]
For upstream, with the next release we will be switching to qt6, so probably we would need kf6 then, but I guess there is no release date for that from our side yet and I very much appreciate the effort :)

**Comment by bbhtt** [comment]
@deepbluev7 Hey, this came up in the kde sdk thread... any idea why you're building libheif without an actual heif decoder or a decoder plugin?

libheif (by extension kimageformats) requires a decoder like libde265 or ffmpeg with hevc to decode hevc/heif media.

**Comment by deepbluev7** [comment]
I think when we tested it, it did decode our test image, but that was quite a while ago and it could be that we messed something up, no idea. It was a user requesting that and also testing the result, I personally don't use it...

**Comment by bbhtt** [comment]
Also, kimageformats with heif is not happening in the KDE SDK due to the patent situation with heif/hevc.

And I don't see many apps building kimageformats on flathub - Krita (because it uses freedesktop sdk), Nheko and gwenview only needs it at the moment.

**Comment by bbhtt** [comment]
> I think when we tested it, it did decode our test image, but that was quite a while ago and it could be that we messed something up, no idea. It was a user requesting that and also testing the result, I personally don't use it...

Ok thanks I can check next week and add it if necessary.

**Comment by deepbluev7** [comment]
> Also, kimageformats with heif is not happening in the KDE SDK due to the patent situation with heif/hevc.

We can probably improve our bundling approach as well and only include the heif plugin (after confirming it works at all still), so that sounds fine. Thanks a lot for your work!

**Pull request merged**
