### PR TITLE
Bump the platform to 5.15-22.08

### PR DESCRIPTION
**Pull request by farribeiro**

### CODE REVIEW

**Comment by deepbluev7** [comment]
Thank you! Someone paying attention to this and updating our deps is very much appreciated!

**Comment by travier** [comment]
This runtime is not ready and we haven't announced it yet. Some users are hitting issues: https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform/issues/7

**Comment by travier** [comment]
Please consider reverting and waiting until we've finished testing it, published the branches for all repos and announced it.

**Comment by deepbluev7** [comment]
Done

**Comment by travier** [comment]
Thanks!

**Pull request merged**
